server:
  address: localhost
  port: 8080

spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haru?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Dlalswo0!!

mybatis:
  type-aliases-package: com.haruMemo.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true